/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {
    @Test
    public void add() {
        Calculator calc = new Calculator();
        int expected = 15;
        int result = calc.add(10, 5);
        assertEquals(expected, result);
    }
}
